# Generated by Django 5.2.13 on 2026-06-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='authenticat_user_id_a3f8f5_idx',
            old_name='authenticat_user_id_8e0f0a_idx',
        ),
    ]
