# Generated by Django 5.2.13 on 2026-06-07 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_product_search_gin_index'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('transaction_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_held', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('HOLDING', 'Holding'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('FROZEN', 'Frozen')], db_index=True, default='HOLDING', max_length=20)),
                ('held_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_trigger', models.CharField(blank=True, choices=[('GRN_SIGNED', 'GRN Signed'), ('AUTO_RELEASE', 'Auto Release (72h)'), ('ADMIN', 'Admin Resolution'), ('DISPUTE', 'Dispute')], max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_account', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_account', to='payments.payment')),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payments.escrowaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='marketplace.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(db_index=True, max_length=20)),
                ('raw_payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'gateway_reference'], name='payments_pa_gateway_1afb65_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['gateway', 'processing_status'], name='payments_we_gateway_00466b_idx'),
        ),
    ]
