# Generated by Django 5.2.13 on 2026-06-07 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_rename_authenticat_user_id_8e0f0a_idx_authenticat_user_id_a3f8f5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_regulated', models.BooleanField(default=False)),
                ('tmda_required', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='marketplace.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brela_registration_number', models.CharField(blank=True, max_length=20)),
                ('tmda_license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('trust_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_delivery_days', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Rolling average delivery time in days.', max_digits=5)),
                ('is_cold_chain_certified', models.BooleanField(default=False)),
                ('cold_chain_cert_expiry', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='authentication.organisation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation__name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='International Nonproprietary Name (INN).', max_length=255)),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='GS1 barcode identifier.', max_length=14)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('is_cold_chain_required', models.BooleanField(default=False)),
                ('temperature_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tmda_registration_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('business_cert', 'Business Certificate'), ('tmda_license', 'TMDA License'), ('tax_clearance', 'Tax Clearance')], max_length=30)),
                ('file', models.FileField(upload_to='supplier_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketplace.supplier')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('storage_conditions', models.CharField(blank=True, max_length=255)),
                ('tmda_batch_cert_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='marketplace.product')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='marketplace_expiry__6feca2_idx'), models.Index(fields=['product'], name='marketplace_product_1c27f4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiry_date__gt', models.F('manufacture_date'))), name='batch_expiry_after_manufacture')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='marketplace_supplie_abef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='marketplace_categor_0fd450_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gtin'], name='marketplace_gtin_d18a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_90c2f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierdocument',
            constraint=models.UniqueConstraint(fields=('supplier', 'document_type'), name='unique_supplier_document_type'),
        ),
    ]
